stages:
  - install
  - build
  - deploy

cache:
  paths:
    - .m2/repository

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts

install:
  stage: install
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn dependency:purge-local-repository dependency:resolve

build:
  stage: build
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn clean compile

deploy:
  stage: deploy
  image: maven:3.9.5-eclipse-temurin-17
  script:
    - mvn package
    - scp target/*.jar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  only:
    - master
