# Stage 1: Build the Node application
FROM node:22-alpine AS build
WORKDIR /app

# Copy dependency files first to utilize cache
COPY package*.json ./
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build -- --configuration production

# Stage 2: Serve with Nginx (Lightweight)
FROM nginx:alpine

# Remove default nginx static assets
RUN rm -rf /usr/share/nginx/html/*

# COPY the build output. 
# IMPORTANT: Check your dist folder structure. 
# In Angular 19, it is usually /dist/project-name/browser
COPY --from=build /app/dist/IndianFoodRestro/browser /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]